services:
  spark-etl:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.10_7_1.10.0_2.12.19
    container_name: spark-etl-job
    working_dir: /workspace
    volumes:
      - .:/workspace
      - sbt-cache:/root/.sbt
      - coursier-cache:/root/.cache/coursier
      - ivy2-cache:/root/.ivy2
    environment:
      - JAVA_OPTS=-Xmx8G
    command: >
      sbt "run --start-date 2019-10-01
        --end-date 2019-11-30
        --input-path .data
        --run-id full_dataset_run
        --execute-wau"

volumes:
  sbt-cache:
  coursier-cache:
  ivy2-cache:
